### ISSUE TITLE
Big breaking changes are coming to to the op-stack bridge contracts

### ISSUE THREAD

**Issue by roninjin10** [rafalum/optimism-python#3]
Just a heads up, the optimism team is making pretty big breaking changes to the SDK in preperation for our testnet launch. If you need guidance let me know. We will be updating the optimism sdk soon which can be used as reference

**Comment by smartcontracts** [comment]
Yeah just for context, the method for selecting the correct output root to use when proving a withdrawal will change with the upcoming changes to the OutputOracle required to get fault proofs to work. Will make sure to ping here when the Optimism SDK is updated so you have a reference implementation.

**Comment by rafalum** [comment]
Thanks for the notice! I added an appropriate disclaimer in the README.

**Comment by rafalum** [comment]
@smartcontracts It seems that the sdk has been removed from the monorepo and has been implemented in viem. Can you confirm this?

**Comment by rafalum** [comment]
Breaking changes have been addressed with https://github.com/rafalum/optimism-python/issues/5
