### ISSUE TITLE
bleu wants to contribute to optimism-python

### ISSUE THREAD

**Issue by mendesfabio** [rafalum/optimism-python#4]
hey @rafalum I'm curious if you're looking for external contributions to bring this Python SDK to feature-parity with the TS one. @bleu-fi has applied to an Optimism Mission to work on a Python SDK but feels like we should contribute to your package instead of starting from scratch.

BTW I followed you on Twitter, if you prefer we can chat there via DMs or in another channel you prefer.

**Comment by rafalum** [comment]
Hey, I messaged you on twitter. 

For others that are interested in contributing, shoot me a message and I will add you as a collaborator.
